version: 2

references:
  common: &common
    docker:
      - image: jorgegueorguiev/hugo

jobs:
  build:
    <<: *common
    steps:
      - checkout
      - run: hugo
      - persist_to_workspace:
          root: .
          paths:
            - public/

  deploy:
    <<: *common
    steps:
      - attach_workspace:
          at: .
      - add_ssh_keys
      - run: apt-get install -y openssh-client
      - run: rsync -av --quiet --delete-after ./public/* ${DEPLOY_USER}@${DEPLOY_HOST}:${DEPLOY_DIRECTORY}

workflows:
  version: 2
  site-deployment:
    jobs:
      - build
      - deploy:
          requires:
            - build
